require:
  - rubocop-performance

AllCops:
  Exclude:
    - "test/**/*"
    - "tests/**/*"
    - "spec/**/*"
    - "vendor/**/*"
  SuggestExtensions: false
  TargetRubyVersion: 2.5

Layout:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Bundler:
  Enabled: false
